---
driver:
  name: vagrant
  require_chef_omnibus: 11.16.4

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: stage

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        cpus: 4
        memory: 1536
      network:
        - - private_network
          - ip: '192.168.33.10'

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[baragon::server]
      - recipe[et_nginx]
      - recipe[baragon::agent]
    attributes:
      java:
        jdk_version: 7
      zookeeper:
        service_style: upstart
