---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  iam_profile_name: nginx-lb
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: remotezk
    run_list:
      - recipe[baragon::service]
      - recipe[nginx]
      - recipe[baragon::agent]

  - name: localzk
    run_list:
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[nginx]
      - recipe[baragon::service]
      - recipe[baragon::agent]
      - recipe[test_baragon_lb::default]
    attributes:
      baragon:
        mocking: true
        zk_hosts:
          - 'localhost:2181'
      zookeeper:
        service_style: upstart
      apt:
        compile_time_update: true

  - name: localzk-source
    run_list:
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[nginx]
      - recipe[baragon::service]
      - recipe[baragon::agent]
      - recipe[test_baragon_lb::default]
    attributes:
      baragon:
        mocking: true
        zk_hosts:
          - 'localhost:2181'
        install_type: source
      zookeeper:
        service_style: upstart
      apt:
        compile_time_update: true
