---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  iam_profile_name: nginx-lb
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev
  attributes:
    baragon:
      mocking: true
      zk_hosts:
        - 'localhost:2181'
    apt:
      compile_time_update: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: agent-service
    run_list:
      - recipe[apt]
      - recipe[zookeeper_minimal]
      - recipe[nginx]
      - recipe[baragon::service]
      - recipe[test_baragon_lb::default]
    includes:
      - ubuntu-16.04
  # We keep this service-only suite around so that we can test the service on 14.04 (the agent
  # recipe no longer supports < 16.04)
  - name: service-only
    run_list:
      - recipe[apt]
      - recipe[zookeeper_minimal]
      - recipe[baragon::service]
    includes:
      - ubuntu-14.04
