---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536
  network:
    - - private_network
      - ip: '192.168.33.10'

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: remotezk
    run_list:
      - recipe[baragon::service]
      - recipe[nginx]
      - recipe[baragon::agent]

  - name: localzk
    run_list:
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[nginx]
      - recipe[baragon::service]
      - recipe[baragon::agent]
      - recipe[test_baragon_lb::default]
    attributes:
      baragon:
        mocking: true
        zk_hosts:
          - 'localhost:2181'
      zookeeper:
        service_style: upstart
      apt:
        compile_time_update: true

  - name: localzk-source
    run_list:
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[nginx]
      - recipe[baragon::service]
      - recipe[baragon::agent]
      - recipe[test_baragon_lb::default]
    attributes:
      baragon:
        mocking: true
        zk_hosts:
          - 'localhost:2181'
        install_type: source
      zookeeper:
        service_style: upstart
      apt:
        compile_time_update: true
