language: ruby
cache:
  directories:
  - "$HOME/.berkshelf"
rvm: 2.2
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
before_install:
- openssl aes-256-cbc -K $encrypted_4d42625e5d39_key -iv $encrypted_4d42625e5d39_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv .chef ~/.chef
- mv .ssh/travis_ci_ec2.pem ~/.ssh/travis_ci_ec2.pem
- mv .ssh/travis_github ~/.ssh/id_rsa
- mv .ssh/trubot.pem ~/.chef/trubot.pem
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
- echo 'client_key "~/.chef/trubot.pem"' >> ~/.chef/knife.rb
- echo 'chef_server_url "https://api.opscode.com/organizations/evertrue"' >> ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.chef/trubot.pem
- chmod 600 ~/.ssh/travis_ci_ec2.pem ~/.chef/encrypted_data_bag_secret ~/.ssh/id_rsa
- ssh-add -D
install:
- eval "$(chef shell-init bash)"
- chef gem install kitchen-ec2 kitchen-sync coveralls
- berks
before_script:
- chef --version
- rubocop --version
- foodcritic --version
script:
- rubocop
- foodcritic .
- chef exec rspec
- kitchen test -d always
notifications:
  slack:
    secure: W96fkcpePaEy9v6aZzRRdssCFd2v2pLTfDDTE2InZQ3nxxIh6/UzSnT74PK1DeecSZPlbZqTENXfkPf599XXcg2UM8NlIPFfY/sDRBAlHUOdhUeBa3yTyV7LVgydk9IP2Q/++5G896lPQ5SiZSSJEgHjxNbyp3W0egRXmMXVB58=
env:
  global:
  - secure: uXNLToUVa/oDQ5/kT+KkVpN+SfpI9ayDPpH5dzihyVmNUJ1rNgM3RILvK3zTkHW8loDAuMdHFlR5ykU1RBwCOU7k5QZJcx1m0eBSl7Q/j4spZXW6CEzZr75gnW1ddQDK85100iUiVNz/QS9VkTMIRzRtZLoXrOEZbBDhDHee+VA=
  - secure: TFFiVCxuGw1OZf+sIdIRte2dX6jE+iNAC7+CCYwMPvaXJvOOBqMEf3YHxYA+6aojixRhLlEMknwZN5tcHgW89KrxQncimRYsMwfp7FaV06MxXYixM796VMjlQ2Qu8QyESEyswEuYpjkr+j/vR7unOM6AV6OLqnqXh/5N6PcvLU8=
  - secure: tU7svc8aupkz9Um4dlZsGOprIYmu9yrFeJWNy11XLYMC8NC2DCgV8HVJLBYlc/MW1J5uhu8BA2FEmVhXrIGGE6JwkgmXrAZyv8mkwGMstDmufkmqfeacROQsPZbwRKXvZnQEcLPyojVHJPSQVuzFPVDiu9eIi/UJIi4NiG6na+A=
  - secure: AsKUNXZXRHhaN11zBrq+keRQarCFpS7DCfw7VB68n9YmdgIepqdHq88Q1gj5pNYL2FVftg9+jhHEYy1o7/mtxCkR5kZtV9swnj8FFD8OswhYs5jeblAdA2g7uOC0lNFXU9mIepCsiF3e4Ri1bgQhPudvMRTRuxptYX71CPSUlu4=
